#   This .travis.yml works to check this repository
# https://github.com/ros-industrial/industrial_core/blob/indigo-devel/.travis.yml
#  Greatly inspired by JSK travis: https://github.com/jsk-ros-pkg/jsk_travis

#sudo: required  # Not required by industrial_ci that uses Docker.
#dist: trusty    # Not required by industrial_ci that uses Docker.
services:
  - docker
# Force travis to use its minimal image with default Python settings
language: generic
notifications:
  #  Whoever receives success and/or failure via email
  email:
    recipients:
#      - accounts@wilselby.com  # Change this to yours should you copy this file.
env:
  global:
    - NOT_TEST_BUILD='false'
    - DEBUG_BASH='true'
    - VERBOSE_OUTPUT='true'
    - CATKIN_CONFIG=--no-install
    - ROS_PARALLEL_TEST_JOBS='-j1'
    - CATKIN_PARALLEL_TEST_JOBS='-p1'
  matrix:
#    - ROS_DISTRO="indigo" ROS_REPO=ros DOCKER_BASE_IMAGE=ros:indigo-ros-core
    - ROS_DISTRO="kinetic" ROS_REPO=ros DOCKER_BASE_IMAGE=ros:kinetic-ros-core ADDITIONAL_DEBS="build-essential python-catkin-tools python-pip ros-kinetic-gazebo-ros-pkgs ros-kinetic-gazebo-ros-control ros-kinetic-joint-state-publisher ros-kinetic-robot-state-publisher ros-kinetic-xacro ros-kinetic-controller-manager ros-kinetic-joint-state-controller ros-kinetic-ros-control"
#    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed DOCKER_BASE_IMAGE=ros:kinetic-ros-core ADDITIONAL_DEBS="build-essential python-catkin-tools python-pip ros-kinetic-gazebo-ros-pkgs ros-kinetic-gazebo-ros-control ros-kinetic-joint-state-publisher ros-kinetic-robot-state-publisher ros-kinetic-xacro ros-kinetic-controller-manager ros-kinetic-joint-state-controller ros-kinetic-ros-control"
#    - ROS_DISTRO="lunar" ROS_REPO=ros DOCKER_BASE_IMAGE=ros:lunar-ros-core
#    - ROS_DISTRO="lunar" ROS_REPO=ros-shadow-fixed DOCKER_BASE_IMAGE=ros:lunar-ros-core
#    - ROS_DISTRO="melodic" ROS_REPO=ros DOCKER_BASE_IMAGE=ros:melodic-ros-core 
#    - ROS_DISTRO="melodic" ROS_REPO=ros-shadow-fixed DOCKER_BASE_IMAGE=ros:melodic-ros-core
matrix:
  allow_failures:
     - ROS_DISTRO="melodic" ROS_REPO=ros DOCKER_BASE_IMAGE=ros:melodic-ros-core ADDITIONAL_DEBS="build-essential python-catkin-tools python-pip ros-melodic-gazebo-ros-pkgs ros-melodic-gazebo-ros-control ros-melodic-joint-state-publisher ros-melodic-robot-state-publisher ros-melodic-xacro ros-melodic-controller-manager ros-melodic-joint-state-controller ros-melodic-ros-control"

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script: 
  - source .ci_config/travis.sh
#  - source ./travis.sh  # Enable this when you have a package-local script 




