[build-system]
build-backend = "setuptools.build_meta"
# use same cmake version as vcpkg (2024.04.26) for pep-517 builds
requires = ["setuptools==69.2.0", "wheel", "cmake==3.24.2", "pybind11==2.12.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]
